### ISSUE TITLE
Krill net supplies trip 2021.06.21

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#10]
- [x] krill net (prepare)
- [x]  Keister net
- [x]  line
- [x]  bridle
- [x]  davit
- [x]  pot puller (test)
- [x]  battery & switch
- [x]  weight
- [x]  load up the boat
- [x] **Shackles**
- [x] **Tools for net**
- [x] **zip ties**

**Comment by pmcelhany** [comment]
We should use the [butterfly loop knot](https://en.wikipedia.org/wiki/Butterfly_loop) for fastening the weight on the line. Unlike an overhand loop, the butterfly loop will not jam and it is easier to undo when we swap nets. (I remembered this knot existed from boat driver class, but had to look up how to do it again.)

**Comment by michaelmaher114** [comment]
sounds like the right knot!
