### ISSUE TITLE
Boat tool box

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#12]
Make a checklist here of tools we should always take out on the boat. Then gather/buy the tools together into a box so we can just grab it when we go out. Something always breaks and it is sort of amazing that there are no tools that live with the boat...
(2021.06.21 KMR)
- [ ] marlin spike
- [x] long handle crescent wrench (purchased but then used in the lab)
- [x] Twine (nylon thin)
- [x] Twine (seine twine thick)
- [ ] replacement shackles (need sizes)
- [x] zip-ties
- [x] needle nose pliers for the sad broken pot puller key 
- [ ] CTD replacement small line (can use seine twine in the interim)
- [ ] crescent wrenches
- [x] wire cutters
- [x] box to hold the tools
- [x] **Home depot (mike 8/17)**

(moved into Motel 6)

**Comment by dmperez89** [comment]
I think most of these things still need to be bought/found. Current contents inclued:
-Small bucket
-Flashlights (2)--functional, but couldn't hurt to charge
-Wire cutters (2)
-Channel locks (2)
-Needle nose pliers (1)
-Cresent wrench (1)
-Zip ties
-Galvanized screw pin anchor bow shackle (pin diameter = 5/8", stock diameter = 1/2")
-Thick twine (not sure if this is what's mentioned above or if we need even thicker twine/rope)

**Comment by KROVINSKI** [comment]
could still use nicer nylon line for CTD and shackles

**Comment by pmcelhany** [comment]
@KROVINSKI @michaelmaher114 If mike goes to fishery supply for a pot puller maybe he can pick up line and shackles for the CTD?

**Comment by pmcelhany** [comment]
@michaelmaher114 @dmperez89 @KROVINSKI 
Please review the lists in this issue to see if there is anything you need to add to the boat box. Let me know once you have had a look then I will close the issue.

**Comment by pmcelhany** [comment]
box complete in 2023
