### ISSUE TITLE
krill jar leak test

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#14]
- [x] Design water test (write short SOP) [DRAFT](https://docs.google.com/document/d/1xWbCwHXSEi0YS3zvN-js6kIJTIZv75Zj3F-w4GNPgcI/edit?usp=sharing)
- [x] Buy more jar lids
- [x] **Buy more silicon** (mcmaster - ordered)
- [x] Gas test in sample jars, lids, and adhoc/bespoke  filters
- [x] Start test 8/27
- [x] Analyze test 
- [x] Run spec app (Paul check treatment file)
- [x] Write/review report on spec repeatability (Danielle)
- [x] plot salinity change [Here](https://docs.google.com/document/d/1AWqVUdO6n2kOFn2gAeNUICjDQ4arQMThNLF9-Ja_y38/edit?usp=sharing)
- [x] Code question on spec
- [x] Present in pCO2 or [H+]? 
- [x] toxicity of foam?
- [x] Add plots to report (final'ish ski report) 
[Here]
(https://docs.google.com/document/d/1WoPwSKQR7cDCuoGqk3ZxNlgjIkBlA6Y-u7jNjkPvjX0/edit)

- [x] create a histogram (in addition to the 4th plot) for deviation from the mean
- [ ] @pmcelhany please look at my histogram
- [x] keep the same plot but use the same y axis 

- [ ] Shallin sign off on report

**Comment by dmperez89** [comment]
[Spec variability/repeatability doc](https://docs.google.com/document/d/1YK7fYdu9xb9Zv9MG9UZjTkkAwMnsgJjWFgHey367FrE/edit?usp=sharing)

**Comment by pmcelhany** [comment]
Thanks, Danielle. Can you please put at header on this (title, author
date)?

In the future, before we start each project, I want everyone on the team to
do an seawater spec pH repeatability test to make sure everything is
working right. Whenever a new person learns spec, they have to do this
first before working with real samples. Can you please draft a new document
that describes this requirement and how to do the test, how to analyze the
data and where to store the results (let's make a new google drive folder
for spec pH repeatability tests). This way, we will have a record of all
the repeatability tests and can easily track spec performance.
thanks
-paul
