### ISSUE TITLE
Krill Collection supplies trip 2021.06.16

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#2]
- [x] Coolers (2-3)--1 on cart, Kate bringing more
- [x] Bubblers--3 functional with batteries, in bucket stack
- [x] Batteries--extra D batteries for bubblers
- [x] Head lamps--only 2
- [x] Gloves--various pairs on cart
- [x] Hand warmers--may be slightly expired, but hopefully better than nothing
- [x] Buckets/cups/spoons/trays--couldn't find spoons, but buckets and cups on cart
- [x] Spot lights (West Marine)--currently charging
- [ ] Ice packs (frozen)--currently in walk in freezer on second floor
- [x] ~~Foul Weather gear~~ --NOT PACKED because everyone seems to have personal gear
- [x] ~~Boots~~ --NOT PACKED because everyone seems to have personal gear
- [x] GoPro
- [x] CTD (little orange probe with AA bats)

**Comment by pmcelhany** [comment]
@KROVINSKI I have boots but not foul weather gear. It would be great to pull some for me. Paul

**Comment by pmcelhany** [comment]
@KROVINSKI I added the GoPro to this list of things to take on the boat. Do we know where it is?

**Comment by pmcelhany** [comment]
@KROVINSKI Were you able to pull some foul weather gear for me?

**Comment by dmperez89** [comment]
I'll grab some from our office. Small grundens coveralls and jacket?

**Comment by pmcelhany** [comment]
Maybe grab small and medium - I can't remember what size I need (there used
to be a jacket with my name in it). I'd also like something in orange
because I'm an autumn.

**Comment by dmperez89** [comment]
I couldn't find a small jacket (but there was a medium), so you might want
to bring anything you might have that would suffice (you may not need
anything). Maybe you can find something in a nice ochre.

**Comment by pmcelhany** [comment]
Trip completed
