### ISSUE TITLE
Formalin SOP

### ISSUE THREAD

**Issue by ShallinBusch** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#22]

**Comment by pmcelhany** [comment]
@ShallinBusch @dmperez89 @KROVINSKI 
Do we have a formalin SOP? Can I close this issue?

**Comment by dmperez89** [comment]
@pmcelhany looks like @KROVINSKI made a pretty detailed one [here](https://docs.google.com/document/d/1LklDQzz9HU838cDbOsmORSIz2R4M35oTPyoFjZucGiA/edit)

**Comment by pmcelhany** [comment]
@dmperez89 @KROVINSKI 
OK, I'm going to close this. Please have Josie, Jenna, and Meredith review it if they will be working with formalin.
