### ISSUE TITLE
Krill Pilot Parts List

### ISSUE THREAD

**Issue by michaelmaher114** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#5]
- [x] big carboy of instant ocean (food grade bucket with lid) 
- [x] Instant ocean in jars before krill collection 
- [x] big carboy of aquarium water (food grade bucket with lid - bubble in fridge)
- [x] 2 bubblers for seawater (do we still have the plug in ones?)--we've got about 3 plug in bubblers and 3 battery powered
- [x] jars (24+ 250mL, 16 medium, 16 large)
- [x] lids (submerged in cooler with containers)
- [x] spoons (for moving krill, can we find the soup spoons?)--I found one spoon to rule them all, so we should probably keep it in the lab, not on the boat
- [x] soaking tub (soak lids and jars in artificial seawater (*soaking in DI water) for at least 24 hours)
- [x] red headlights / ~~red flashlights?~~ (we will find out how hard it is to see the purple females)
- [x] Chambers turned on and at temp (lights off?)
- [x] water change filter (may need to make)
- [x] test auto pipettes
- [ ] data sheets -chamber, ID, egg count, day 4 egg count(?)
- [ ] jar labels
- [x] formalin & buffer (from Correigh Green)
- [x] clicker counters (maybe near artemia cones or a drawer?)
- [x] Chamber shelves
- [x] **salinity sensor (fix and calibrate!)**
- [ ] **Buy more conductivity calibration standards** (ordered - fischer; should ship/charge before deadline)

**Comment by KROVINSKI** [comment]
> * [ ]  big carboy of instant ocean (food grade bucket with lid)
> * [ ]  Instant ocean in jars before krill collection
> * [x]  big carboy of aquarium water (food grade bucket with lid)
> * [ ]  2 bubblers for seawater (do we still have the plug in ones?)
> * [x]  jars (32 or more jars, 16 large, 16 small)
> * [ ]  lids (somewhere at Montlake, need to locate)
> * [ ]  spoons (for moving krill, can we find the soup spoons?)
> * [x]  soaking tub (soak lids and jars in artificial seawater for at least 24 hours)
> * [ ]  red headlights / red flashlights? (we will find out how hard it is to see the purple females)
> * [ ]  Chambers turned on and at temp (lights off?)
> * [ ]  water change filter (may need to make)
> * [ ]  test auto pipettes
> * [ ]  data sheets -chamber, ID, egg count, day 4 egg count(?)
> * [ ]  jars (50ml conical?) to preserve sample at the end of experiment
> * [ ]  jar labels
> * [ ]  formalin & buffer
> * [ ]  clicker counters (maybe near artemia cones or a drawer?)
> * [ ]  Chamber shelves

(2021.06.14 check off items as packed or as completed)

**Comment by dmperez89** [comment]
Could not find red flashlights or soup spoons. If anyone knows where they might be....

**Comment by pmcelhany** [comment]
Should we get a take out order of wonton soup  everyone?

**Comment by pmcelhany** [comment]
@KROVINSKI @michaelmaher114 Lets see if we can get some formalin from Correigh, but let's also order 4 liters for formalin for ourselves. Maybe Kate can add it to Kathleen's list?

**Comment by pmcelhany** [comment]
@KROVINSKI @michaelmaher114 We need to order new lids for the krill jars. I'll look at my filemaker to see if I can find out more about where those jars and lid came from...

**Comment by pmcelhany** [comment]
@michaelmaher114 @KROVINSKI  I could not find those exact jars in my foray into filemaker. the 89/400 lid (if that is what you just bought) seems to be the industry standard and if they don't fit the existing jars, then maybe we should give up and just order a new jar/lid combo. That might be our fastest option if we do an expedited order through US Plastics.

**Comment by pmcelhany** [comment]
@KROVINSKI  Is this one really done? Seems like we don't have everything checked off on the list. Maybe OK to close this one and open some new issues with specific missing pieces like formalin and jars. Let's review this afternoon before closing this.
