### ISSUE TITLE
Krill pilot schedule (update when we catch krill...)

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#6]
Course of Action 04 Starting 22JUN21 Tuesday
Collection
- [x] 6/22 TUE DAY 00 (catching krill and make saltwater) @pmcelhany @dmperez89  are we doing any SPEC monitoring?

Observation & Water Chemistry/Changes
- [x] 6/23 WED DAY 01 (count eggs, remove dead/spent krill)
- [x] 6/24 THR DAY 02 (count eggs, remove dead/spent krill)
- [x] 6/25 FRI DAY 03 (count eggs, remove dead/spent krill, change water)
- [x] no observation over the weekend
- [x] 6/27 MON DAY 06 (N/A) 
- [x] 6/28 TUE DAY 07 (N/A)

Preserving Samples & Project Conclusion
- [x] 6/29 WED DAY 07 (counting, obsrvs, formalin addt) *hatch success dependent
- [x] 6/30 THR DAY 08 (counting, obsrvs, 2nd day of formalin addt) 
- [x] 7/01 FRI DAY 09 (counting, obsrvs, 3rd day of formalin addt) 
- [x] 7/02 SAT DAY 10 (counting, obsrvs, 4th/final day of formalin addt)* Project End

**Comment by pmcelhany** [comment]
@KROVINSKI can you update this when we find out when the boat is fixed?

**Comment by pmcelhany** [comment]
@KROVINSKI Can you please update krill schedule now that 6/16 is krill catch'n day?

**Comment by KROVINSKI** [comment]
closing the issue for the timeline of Krill Pilot Schedule
