### ISSUE TITLE
Pilot summary report

### ISSUE THREAD

**Issue by pmcelhany** [NWFSC-OA-lab/krl_lrv_ph_temp_2021#7]
- [x] Mike review [pilot SOP](https://docs.google.com/document/d/1ATipPVVF8c0mi15faMC7WVfQfG6NwespVUnQaoxcRrk/edit#heading=h.in8sw0sqxva1)

Draft of SOP "What Actually Happened" [here](https://drive.google.com/file/d/1CMfJOgTsgJMtnJocaiiUpKrMcSlvhKl7/view?usp=sharing)

- [x] Shallin review pilot SOP
- [x] Review Anna's paper or other literature with formalin info (Danielle/Kate)
- [x] Shallin sign off on SOP/report

**Comment by michaelmaher114** [comment]
look back through Anna's methods.

**Comment by michaelmaher114** [comment]
adding link to the krill exp folder
https://drive.google.com/drive/u/0/folders/1Er0LKo1OfFajMm_FkOQwqBdnyGlG7vtr

**Comment by dmperez89** [comment]
[A google doc of some notes I took on papers on krill in formalin](https://docs.google.com/document/d/1sRChWNIVLfIJNqtqXdzqrcMUCH7Y-WORaSwx4ul7kbI/edit)

Basically everything is in either 5% or 10% buffered formalin, but I haven't found much that goes into any greater detail.
